apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-app
  template:
    metadata:
      labels:
        app: download-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: download-app
          image: dfernandesapoioprodesp/download-nfe-app:vIMAGE_TAG
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: download-app
spec:
  selector: 
    app: download-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
