name: PIPELINE-CI-CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build da imagem
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            dfernandesapoioprodesp/download-nfe-app:v${{github.run_number}}
            dfernandesapoioprodesp/download-nfe-app:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Autenticacao Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_P }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_P }}
          export_default_credentials: true
          install_components: kubectl

      - name: Validar Autenticacao
        run: |
          gcloud auth list
          gcloud config list

      - name: Busca credenciais do cluster
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME_P }} --region ${{ secrets.GKE_REGION }}

      - name: Atualiza IMAGEM no deployment
        run: |
           sed -i "s|IMAGE_TAG|${{ github.run_number }}|g" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
